package com.demo.phonebook.service;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.demo.phonebook.entity.Phonebook;
import com.demo.phonebook.repository.PhonebookRepository;

@Component
public class PhonebookService {
	
	@Autowired // This means to get the bean called phonebookRepository
    			// Which is auto-generated by Spring, we will use it to handle the data
	private PhonebookRepository phonebookRepository;
	
	public PhonebookService(PhonebookRepository phonebookRepository) {
		this.phonebookRepository = phonebookRepository;
	}
	
	public Phonebook addUser(Phonebook phonebook) {
    	return phonebookRepository.save(phonebook);
    }
	
	public void deleteUserById(Long id) {
    	phonebookRepository.deleteById(id);
    	return;
    }
	
	public Phonebook updateUser(Phonebook phonebook) {
    	Optional<Phonebook> updated = phonebookRepository.findById( phonebook.getId());
    	updated.get().setFirstName(phonebook.getFirstName());
    	updated.get().setLastName(phonebook.getLastName());
    	updated.get().setPhone(phonebook.getPhone());
    	updated.get().setId(phonebook.getId());
    	return phonebookRepository.save(updated.get());
    }
	
	public Iterable<Phonebook> getAllUsers() {
    	return phonebookRepository.findAll();
    }
	
	public Phonebook getUserById(Long id) {
		Optional<Phonebook> updated = phonebookRepository.findById(id);
		return updated.get();
	}
	
}
